sudo: required
dist: trusty
language: cpp
compiler:
  - clang
  - gcc
env:
  - LUAJIT=OFF
  - LUAJIT=ON
cache: apt
addons:
  apt:
    sources:
      - sourceline: 'ppa:kzemek/boost'
    packages:
      - liblua5.2-dev
      - libluajit-5.1-dev
      - libmysqlclient-dev
      - libpugixml-dev
      - libboost1.58-dev
      - libboost-system1.58-dev
      - libboost-iostreams1.58-dev
before_script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DUSE_LUAJIT=${LUAJIT} ..
script: make -j2
