image: Visual Studio 2017

shallow_clone: true

platform:
  - x86

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true

only_commits:
  files:
    - src/
    - vc14/
    - appveyor.yml

install:
  - cmd : vcpkg install boost-iostreams:x86-windows
  - cmd : vcpkg install boost-asio:x86-windows
  - cmd : vcpkg install boost-system:x86-windows
  - cmd : vcpkg install boost-filesystem:x86-windows
  - cmd : vcpkg install boost-variant:x86-windows
  - cmd : vcpkg install boost-lockfree:x86-windows
  - cmd : vcpkg install cryptopp:x86-windows
  - cmd : vcpkg install luajit:x86-windows
  - cmd : vcpkg install libmariadb:x86-windows
  - cmd : vcpkg install pugixml:x86-windows
  - cmd : vcpkg install mpir:x86-windows

build:
  parallel: true
  # MSBuild verbosity level
  #verbosity: detailed

cache:
  - c:\tools\vcpkg\installed\

artifacts:
  - path: vc14\**\theforgottenserver*.exe
  - path: vc14\**\*.dll
