image: Visual Studio 2017

shallow_clone: true

platform:
  - x64

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true

only_commits:
  files:
    - src/
    - vc14/
    - appveyor.yml

install:
  - cmd : vcpkg install boost:x64-windows
  - cmd : vcpkg install luajit:x64-windows
  - cmd : vcpkg install libmysql:x64-windows
  - cmd : vcpkg install pugixml:x64-windows
  - cmd : vcpkg install mpir:x64-windows

build:
  parallel: true
  # MSBuild verbosity level
  #verbosity: detailed

cache:
  - c:\tools\vcpkg\installed\

artifacts:
  - path: vc14\**\theforgottenserver.exe
