os: Visual Studio 2015

branches:
  only:
    - master

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true

environment:
    BOOST_ROOT: C:\Libraries\boost_1_62_0
    TFSSDKDir: tfs-sdk-3.2

install:
    - ps: if (-not (Test-Path tfs-sdk-3.2)) { Start-FileDownload https://static.otland.net/dl/tfs-sdk-3.2.zip; 7z x tfs-sdk-3.2.zip }

cache:
    - tfs-sdk-3.2 -> appveyor.yml