name: Build on Ubuntu

on:
  push:
    branches:
      - master
      - v*

    paths:
      - cmake/**
      - src/**
      - CMakeLists.txt
      - CMakePresets.json

  pull_request:
    paths:
      - cmake/**
      - src/**
      - CMakeLists.txt
      - CMakePresets.json

jobs:
  build-ubuntu:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Get latest CMake
        # Using 'latest' branch, the latest CMake is installed.
        uses: lukka/get-cmake@latest

      - name: Install dependencies
        run: >
          sudo apt update &&
          sudo apt install build-essential libluajit-5.1-dev libmysqlclient-dev
          libboost-date-time-dev libboost-system-dev libboost-iostreams-dev libboost-filesystem-dev
          libpugixml-dev libcrypto++-dev libfmt-dev

      - name: Build with cmake
        uses: lukka/run-cmake@v10
        with:
          buildPreset: ninja
          configurePreset: ninja

      - name: Upload artifact binary
        uses: actions/upload-artifact@v3
        with:
          name: ubuntu-tfs-amd64-${{ github.sha }}
          path: ${{ runner.workspace }}/build/tfs
