name: Build on Ubuntu

on:
  push:
    branches:
      - master
      - v*

    paths:
      - src/**
      - meson.build

  pull_request:
    paths:
      - src/**
      - meson.build

jobs:
  build-ubuntu:
    runs-on: ubuntu-20.04
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: >
          sudo apt update -qq &&
          sudo apt install -yqq git meson ninja-build build-essential libmysqlclient-dev \
            libboost-date-time-dev libboost-system-dev libboost-iostreams-dev libboost-filesystem-dev \
            libcrypto++-dev

      - name: Build with meson
        run: meson setup -D buildtype=release ${{ runner.workspace }}/build && ninja -C ${{ runner.workspace }}/build

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: ubuntu-tfs-amd64-${{ github.sha }}
          path: ${{ runner.workspace }}/build/tfs
