name: Check code style

on:
  push:
    branches:
      - master
      - v*

    paths:
      - .clang-format
      - src/**

  pull_request:
    paths:
      - .clang-format
      - src/**

jobs:
  check-format:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: >
          sudo apt-get update &&
          sudo apt-get install clang-format

      - name: Check code style
        run: clang-format -n -style=file --Werror src/*.{cpp,h}
