name: Check code style

on:
  push:
    branches:
      - master
      - v*

    paths:
      - .clang-format
      - .github/workflows/clang-format.yml
      - src/**

  pull_request:
    paths:
      - .clang-format
      - .github/workflows/clang-format.yml
      - src/**

  workflow_dispatch:

jobs:
  check-format:
    runs-on: ubuntu-latest

    container:
      image: ubuntu:rolling

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: apt update -q && apt install -yq clang-format

      - name: Check code style
        run: clang-format -n -style=file --Werror src/*.{cpp,h}
