name: Lua syntax check

on:
  push:
    branches:
      - master
      - FixChecks
      - v*
      
    tags:
      - v*
      
  pull_request:
    paths:
      - cmake/**
      - src/**
      - CMakeLists.txt
      - .github/**

jobs:
  luac:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: leafo/gh-actions-lua@v8.0.0

      - name: Test Lua syntax
        run: find data/ -name '*.lua' -print0 | xargs -0 -n1 luac -p
