name: Unit tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: >
          sudo apt update -q &&
          sudo apt install -yq git cmake build-essential libluajit-5.1-dev libmysqlclient-dev
          libboost-date-time-dev libboost-system-dev libboost-iostreams-dev libboost-filesystem-dev
          libboost-test-dev libpugixml-dev libcrypto++-dev libfmt-dev

      - name: Build with CMake
        uses: lukka/run-cmake@v10
        with:
          buildPreset: ninja
          configurePreset: ninja
          configurePresetAdditionalArgs: "['-DENABLE_TESTING=ON']"
          testPreset: ninja
