name: Unit tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: >
          sudo apt update -q &&
          sudo apt install -yq git cmake build-essential libluajit-5.1-dev libmysqlclient-dev
          libboost-date-time-dev libboost-system-dev libboost-iostreams-dev libboost-filesystem-dev
          libboost-test-dev libpugixml-dev libcrypto++-dev libfmt-dev

      - name: Build with cmake
        uses: ashutoshvarma/action-cmake-build@master
        with:
          build-dir: ${{ runner.workspace }}/build
          # will set the CC & CXX for cmake
          cc: gcc
          cxx: g++
          # Extra options pass to cmake while configuring project
          configure-options: -DENABLE_TESTING=ON -DUSE_LUAJIT=on
          # run build using '-j [parallel]' to use multiple threads to build
          parallel: 2
          run-test: true
